### ISSUE TITLE
Crash when shift-right clicking a player (Modpack)

### ISSUE THREAD

**Issue by opee2012** [WinterWolfSV/Transferable_Pets#1]
I made a custom modpack and when I shift right click a player, I crash and have the error below.

[crash-2023-11-10_18.46.45-client.txt](https://github.com/WinterWolfSV/Transferable_Pets/files/13323806/crash-2023-11-10_18.46.45-client.txt)

**Comment by WinterWolfSV** [comment]
Hey! Sorry about the inconvenience. I was able to reproduce the issue and fixed it. The newest version, 1.0.4 can now be downloaded on [modrinth](https://modrinth.com/plugin/transferable-pets/version/1.0.4) which addresses the issue you experienced.
